### ISSUE TITLE
CocoaPod support

### ISSUE THREAD

**Issue by everic** [evernote/evernote-cloud-sdk-ios#1]
support cocoapod

**Comment by everic** [comment]
@sonsongithub Hey, I decided to stick with the build script for a while. As using the iOS 8 dynamic framework still requires to use lipo command to combine built products for sim and device. Can you make a pull request to create a podspec file to release this on cocoapods? Thank you.

**Comment by sonsongithub** [comment]
Oh... Recently, I don't use it on iOS8.
I will create pods file later.
Thanks.

**Comment by siuying** [comment]
I've been using this [podspec](https://gist.github.com/siuying/978cc50d7d3de121d66e)

**Comment by sonsongithub** [comment]
May I use your podspec file, and register it into CocoaPods repository?

**Comment by siuying** [comment]
I think we could do it once the repo have a tagged version. Or maybe @everic can do it himself?

**Comment by sonsongithub** [comment]
I agree @siuying said.
How about you, @everic ?

**Comment by everic** [comment]
![screen shot 2015-01-28 at 4 11 08 pm](https://cloud.githubusercontent.com/assets/7154385/5949935/6a2e9d2a-a708-11e4-8e08-b0f014f7621b.png)

**Comment by everic** [comment]
Submitted to trunk. Not accepted yet.

**Comment by sonsongithub** [comment]
Sounds good, thank you!

**Comment by everic** [comment]
Hi @sonsongithub @siuying Cocoapod gurus
I've successfully published my podspec file
https://github.com/CocoaPods/Specs/blob/master/Specs/evernote-cloud-sdk-ios/2.0/evernote-cloud-sdk-ios.podspec.json

But I cannot use the pod just yet. It's been a couple of hours already.
![screen shot 2015-01-28 at 8 05 31 pm](https://cloud.githubusercontent.com/assets/7154385/5952304/10113ec6-a729-11e4-8e6a-9513298619ff.png)

Does someone from the Cocoapods communities needs to approve this? Or is there something that I'm missing?

Thanks guys

**Comment by siuying** [comment]
I cant find the pods too. Very strange, from the screenshot you should have pushed it already.

**Comment by siuying** [comment]
After I type `pod repo update` then i can find the pod `pod search 'evernote-cloud-sdk-ios'`.

**Comment by everic** [comment]
@siuying 
I did the same trick and it worked!
I was not able to pod repo update that I had to delete the local master and 'pod setup' again

Anyway, this ticket should be fixed. I verified with one of my test app and it works fine.

**Comment by sonsongithub** [comment]
Thank you very much for your work!
