### ISSUE TITLE
Version 2.0.3 podspec is missing

### ISSUE THREAD

**Issue by aviramuse** [evernote/evernote-cloud-sdk-ios#100]
Missing [here](https://github.com/CocoaPods/Specs/tree/master/Specs/evernote-cloud-sdk-ios) and therefore couldn't be installed.

**Comment by everic** [comment]
Should be resolved by having version 2.0.5 available on Cocoapods. Please try and let me know.

**Comment by aviramuse** [comment]
It works, thanks @everic
