### ISSUE TITLE
Cannot build project, evernote-cloud-sdk-ios-umbrella.h cannot see .m source files

### ISSUE THREAD

**Issue by crystalclear506** [evernote/evernote-cloud-sdk-ios#104]
"Could not build Objective-C module evernote_cloud_sdk_io"

I installed the SDK via Cocoapods, the project is written in Swift. However I couldn't build the project since the umbrella.h cannot see any .m files even though every files are already in the project. I don't see any problem with header files though.

![](http://i.stack.imgur.com/Itl5Q.png)

![](http://i.stack.imgur.com/zuEAu.png)

**Comment by everic** [comment]
What is this umbrella.h file? Is it automatically generated by Cocoapods for Swift projects? Can you make a sample project for this issue for me to checkout? Thanks.

**Comment by crystalclear506** [comment]
Yes, umbrella.h is auto-generated by Cocoapods, I created a new sample project with the given issue here in this link "https://github.com/crystalclear506/CocoaEN" Please note that the only code I added after I import the library from Cocoapods is "import evernote_cloud_sdk_ios" in ViewController.swift, and that's exactly when this issue arises. Thanks in advance.

**Comment by jimdusseau** [comment]
Can you try out 2.0.6 and close this issue if it fixes things for you?

**Comment by crystalclear506** [comment]
@jimdusseau I still have an error, it's a different error though

Here it is:
```
/CocoaEN/Pods/evernote-cloud-sdk-ios/evernote-sdk-ios/ENSDK/Advanced/Utilities/ENMLWriter/ENXMLUtils.h:30:9: Include of non-modular header inside framework module 'evernote_cloud_sdk_ios.ENXMLUtils' 
```
