### ISSUE TITLE
CocoaPod import issue - ENSDK.h file not found

### ISSUE THREAD

**Issue by hyouuu** [evernote/evernote-cloud-sdk-ios#105]
Used latest CocoaPod (with use_frameworks!) & Xcode 6.4 with Swift, and when printing out any thing in LLDB, if I import ENSDK in the Swift-ObjC Bridging header like:
# import <ENSDK/ENSDK.h>

I get the following errors:

error: Error in auto-import:
failed to get module 'Noter' from AST context:
/Users/hyou/Dropbox/dev/iOS/Pendo/Noter-Bridging-Header.h:20:9: error: 'ENSDK/ENSDK.h' file not found
# import <ENSDK/ENSDK.h>

```
    ^
```

failed to import bridging header '/Users/hyou/Dropbox/dev/iOS/Pendo/Noter-Bridging-Header.h'A fatal parse error has occurred.  LLDB may become unstable; please restart your debug session as soon as possible.

Otherwise, if I import ENSDK like:
# import "ENSDK.h"

I get the following:

error: Error in auto-import:
failed to get module 'Noter' from AST context:
/Users/hyou/Dropbox/dev/iOS/Pendo/Noter-Bridging-Header.h:19:9: note: while building module 'evernote_cloud_sdk_ios' imported from /Users/hyou/Dropbox/dev/iOS/Pendo/Noter-Bridging-Header.h:19:
# import "ENSDK.h"

```
    ^
```

<module-includes>:1:9: note: in file included from <module-includes>:1:
# import "/Users/hyou/Dropbox/dev/iOS/Pendo/Pods/Target Support Files/evernote-cloud-sdk-ios/evernote-cloud-sdk-ios-umbrella.h"

```
    ^
```

/Users/hyou/Dropbox/dev/iOS/Pendo/Pods/Target Support Files/evernote-cloud-sdk-ios/evernote-cloud-sdk-ios-umbrella.h:6:9: error: 'EDAMErrors.m' file not found
# import "EDAMErrors.m"

```
    ^
```

/Users/hyou/Dropbox/dev/iOS/Pendo/Noter-Bridging-Header.h:19:9: error: could not build module 'evernote_cloud_sdk_ios'
# import "ENSDK.h"

```
    ^
```

failed to import bridging header '/Users/hyou/Dropbox/dev/iOS/Pendo/Noter-Bridging-Header.h'A fatal parse error has occurred.  LLDB may become unstable; please restart your debug session as soon as possible.

**Comment by everic** [comment]
Hello. Please provide a sample Swift project with Cocoapods integration and attach it to the bug. It would make resolving this bug much faster. Thank you.

**Comment by hyouuu** [comment]
When creating a sample project, the bridge header would not import at all - please check out: https://github.com/hyouuu/ENSDKSample

**Comment by everic** [comment]
Hello. I just updated some headers and published a new version 2.0.5 to Cocoapods. Let me know if it works for you. It might take a while to appear on Cocoapods.

**Comment by hyouuu** [comment]
Updated to 2.0.5 and apparently it's still an issue... Have you tried to compile the sample project at all?

**Comment by hyouuu** [comment]
Maybe you want to take a look at another library as an example? This one works for me:
https://github.com/ViccAlexander/Chameleon/blob/master/ChameleonFramework.podspec

**Comment by hyouuu** [comment]
Here is another person with the same issue: http://stackoverflow.com/questions/31612807/file-not-found-error-in-xcode-using-evernote-ios-api-in-swift-with-cocoapods

**Comment by seanLee** [comment]
@hyouuu So how did u solve the issue finally?It seems that I meet the same issue with you.

**Comment by hyouuu** [comment]
@seanLee I tried to build locally but are facing other issues, so I'm postponing Evernote integration for now... let me know if you find a way around it or @everic could fix it

**Comment by RongchangLei** [comment]
For using CocoaPod for evernote-cloud-sdk-ios, you should do 

```
#import <evernote-cloud-sdk-ios/ENSDK.h>
```
instead of 
```
#import <ENSDK/ENSDK.h>
```
Hope this can solve you guys' issue.

**Comment by jimdusseau** [comment]
Can you try out 2.0.6 and close this issue if it fixes things for you?

**Comment by D-32** [comment]
@jimdusseau version 2.0.6 works for me inside a swift project. Just needed to use `import evernote_cloud_sdk_ios`. Could we push 2.0.6 to the cocoapods trunk?

**Comment by jimdusseau** [comment]
If you've reclaimed control of the cocoa pods project, please do.

**Comment by Chaosspeeder** [comment]
I will give it a try. Thank you

**Comment by gregyoung14** [comment]
Using Xcode 8, Objective C, and "pod 'box-ios-sdk', :git => 'https://github.com/box/box-ios-sdk.git'" to get 2.0.6 it only works if you do #import "ENSDK/ENSDK.h" with quotes.

**Comment by imougy** [comment]
Fixed now.
