### ISSUE TITLE
ENNote setTitle strips all whitespace if there is a trailing whitespace in string

### ISSUE THREAD

**Issue by Jaymon** [evernote/evernote-cloud-sdk-ios#107]
Tested with the latest version 2.0.5 sdk.

Snippet to reproduce:

```obj-c
// Evernote sdk imported using...
// #import <ENSDK.h>

NSString *title = @"Foo Bar Baz Che "; // notice the trailing whitespace
ENNote *enote = [ENNote new];
enote.title = title;
NSLog(@"%@", enote.title);
```

The `NSLog` will output:

```
FooBarBazChe
```

This seems like an unintended consequence of the NSString+ENScrubbing `en_scrubUsingRegex:withMinLength:maxLength:invalidCharacterReplacement:` method doing sanity checking on the title. 

Specifically, the regex `EDAM_NOTE_TITLE_REGEX` gets a match when there is a whitespace at the end of the string, this then causes each character to be checked one by one, and since each `@" "` will fail the check and trigger the replacement string (which is **nil**) to be added to the title instead of the original space, all whitespace gets stripped.

Since the easiest fix is to just trim the string before running it through the regex I figured I would submit a pull request but then I thought I would make sure this is, indeed, unintended behavior since this might be by design?

In the meantime, I'm just trimming the string on my side before setting the title :)

**Comment by everic** [comment]
This is by design. We're trimming the trailing white spaces in the note titles as our service expect the clients to do so, and all the Evernote clients currently do this.
