### ISSUE TITLE
EDAMNote content vs ENMLWriter contents

### ISSUE THREAD

**Issue by heitortsergent** [evernote/evernote-cloud-sdk-ios#108]
On the Advanced API guide "[Hello Word Example](https://github.com/evernote/evernote-cloud-sdk-ios/blob/master/Working_with_the_Advanced_(EDAM)_API.md#hello-world-example)" there's a line:

```objc
NMLWriter * writer = [[ENMLWriter alloc] init];
...
EDAMNote * note = [[EDAMNote alloc] init];
...
note.contents = writer.contents;
```

EDAMNote contents property is actually `content`: https://github.com/evernote/evernote-cloud-sdk-ios/blob/master/evernote-sdk-ios/ENSDK/Advanced/EDAM/EDAMTypes.h#L384

Should the NMLWrite property be changed to `content` as well, or EDAMNote's to `contents`?

**Comment by everic** [comment]
Should be note.content. Thanks!
