### ISSUE TITLE
"ENSDK.h file not found" error when using ENSDK.Framework and EDAM API

### ISSUE THREAD

**Issue by heitortsergent** [evernote/evernote-cloud-sdk-ios#109]
This error happens in three different files: `ENSDKAdvanced.h`, `ENNoteStoreClient.h`, `ENSDKPrivate.h`

Steps to reproduce:
- Clone repository from GitHub
- Run the framework build script inside `./scripts`
- Create new Single Page Application project
- Copy `ENSDK.framework` and `ENSDKResources.bundle` inside new project
- Add `#import <ENSDK/Advanced/ENSDKAdvanced.h>` to AppDelegate and try to create an ENSession object with: `ENSession *session;`

I could fix this by changing the line `#import ENSDK.h` to `#import "../ENSDK.h"` in the three classes I mentioned above, but that doesn't seem like a good solution to use with the SDK.

**Comment by hyouuu** [comment]
Should be related to #105 - please fix them altogether :)

**Comment by jimdusseau** [comment]
Can you try out 2.0.6 and close this issue if it fixes things for you?
