### ISSUE TITLE
Error getting the evernote Token

### ISSUE THREAD

**Issue by thedude66** [evernote/evernote-cloud-sdk-ios#116]
I need to get the evernote user token and using the ENCredentials authenticationToken property i'm getting this error
Error getting password from keychain: Error Domain=com.samsoffes.ENSSKeychain Code=-1001 "ENSSKeychainErrorBadArguments" UserInfo={NSLocalizedDescription=ENSSKeychainErrorBadArguments}

**Comment by jimdusseau** [comment]
I'd suggest setting a breakpoint in `+ (NSError *)errorWithCode:(OSStatus) code` and working backwards through the stack to see which method in `ENSSKeychainQuery` is returning this error. Hopefully it's just a configuration issue where `service` or `account` is unset.
