### ISSUE TITLE
ENSaveToEvernoteActivity file not found

### ISSUE THREAD

**Issue by mihahribar** [evernote/evernote-cloud-sdk-ios#117]
Added `pod 'evernote-cloud-sdk-ios'` to `Podfile`, included `<ENSDK/ENSDK.h>` in my `AppDelegate` and hit build - got error:

```
'ENSaveToEvernoteActivity.h' file not found
```

Error is in `ENSDK.h` line 39, which is this line:

```objc
#import "ENSaveToEvernoteActivity.h"
```

I'm using build 2.0.2 because 2.0.5 deployment target is iOS8 and I'm using iOS7. Is my only option to use the old 1.x version or am I missing something?

**Comment by jimdusseau** [comment]
Yes. The current version requires iOS 8+

**Comment by jimdusseau** [comment]
I think I have your "file not found" error fixed. Can you try out 2.0.6 and close this issue if it fixes things for you?

**Comment by mihahribar** [comment]
I have since dropped iOS7 support, so consider the matter closed.

**Comment by ehlersd** [comment]
Sorry to reopen this, but I'm having the same error now with the latest.

**Comment by ehlersd** [comment]
Okay, looks like it was in my podfile, I had specified 

`platform :ios, "7.0"`

Even though I'm using 9.3 for the minimum.  Updating that allowed the 2.0.5 pod version to be used.  Making that change resolved the issue.
