### ISSUE TITLE
Fail to upload note in the official environment.

### ISSUE THREAD

**Issue by Limon-catch** [evernote/evernote-cloud-sdk-ios#122]
When I work in sandbox environment, I can add note to my sandbox Evernote account, 
but I failed when I tried to upload note in the official environment.

Can you help me ? 😭

**Comment by jimdusseau** [comment]
When you first generate a developer key, it only works against the sandboxed environment. Keys have to be "activated" for use on production. There's a form to do that on this page: https://dev.evernote.com/support/

**Comment by Limon-catch** [comment]
I found out something. I set the host to "app.yinxiang.com", and then chose the 'Evernote-China' to login. 
On this way, I add a note Successfully.
Can I set the host to `nil` for Apps in China ?
[](https://raw.githubusercontent.com/Limon-catch/EvernoteSimple/master/image/Evernote.png)

**Comment by Limon-catch** [comment]
```swift
let host: String? = canOpenURL(URLString: "en://") ? nil : "app.yinxiang.com"
ENSession.setSharedSessionConsumerKey(Configs.Evernote.appID, consumerSecret: Configs.Evernote.appKey, optionalHost: host)
```
