### ISSUE TITLE
authenticateWithViewController problem

### ISSUE THREAD

**Issue by nix7965** [evernote/evernote-cloud-sdk-ios#125]
When I execute this part,
ENSession *session = [ENSession sharedSession];
[session authenticateWithViewController:self preferRegistration:NO completion:^(NSError *error) {
    if (error) {

```
} 
```

}];

I got error which may be related to 'authenticateWithViewController:preferRegistration:completion:' with View controller

<UINavigationController: 0x12ed36440> on <ViewController: 0x12ee1f000> whose view is not in the window hierarchy! 
<UINavigationController: 0x12ed36440> on <ViewController: 0x12ee1f000> whose view is not in the window hierarchy!
2016-04-02 15:25:12.148 [1232:17517] Received error HTTP response code: 401
2016-04-02 15:25:12.148 [1232:17517] <html>
....

Anybody knows how to solve it? Seems like ViewControlloer problem. But, I don't have much knowledge in iOS programming

**Comment by imougy** [comment]
You need to pass a viewController, from your code sample, we don't know what `self` is.
Closing it and reopen if you still have issue.
