### ISSUE TITLE
App Transport Security (ATS) Settings

### ISSUE THREAD

**Issue by agiletortoise** [evernote/evernote-cloud-sdk-ios#132]
With Apple announcing that App Transport Security (ATS) exceptions will not be allowed by the end of the year, I'm wondering if there are recommended info.plist settings to ensure connections to the backend from the SDK will be allowed under ATS.

For details on the new rules, see WWDC session #706, What's New in Security (https://developer.apple.com/videos/play/wwdc2016/706/)

**Comment by imougy** [comment]
Evernote uses `https`, so don't worry about the SDK side.
