### ISSUE TITLE
Is there any Dev Support available in Evernote?

### ISSUE THREAD

**Issue by akshaynhegde** [evernote/evernote-cloud-sdk-ios#136]
This has been a very long time and there is no update to the Evernote iOS SDK. Even the pod file hasn't been updated over a year!

We are having trouble integrating Evernote SDK with our iOS app written in swift and its very essential for us to get this fixed. There literally zero support anywhere over the internet. Emails, twitter, SO, GitHub, every single communication channel seems to be dead.

Can you please update if you indeed are supporting or trying to get in touch is a lost cause..?

**Comment by akhaku** [comment]
Hi! We don't currently have a dedicated developer relations team so a few of us have been responding to questions on SO and github in our spare time. The ones who are responding don't have iOS experience, but if you have specific questions we can try and look in someone from our iOS team, and they should be able to help.

**Comment by akshaynhegde** [comment]
@akhaku , Thank you. 

We are facing problems integrating the Evernote SDK in swift framework.

Here is the [GitHub Issue](https://github.com/evernote/evernote-cloud-sdk-ios/issues/135)
and [SO Question](http://stackoverflow.com/questions/39062707/unable-to-import-the-evernote-framework-into-swift-project)

**Comment by akhaku** [comment]
Awesome, I pinged some of the iOS guys last night and it looks like they responded. Should be all set, but definitely follow up on #135 and let us know.
