### ISSUE TITLE
Crash when encountering empty values (ENHTMLtoENMLConverter)

### ISSUE THREAD

**Issue by D-32** [evernote/evernote-cloud-sdk-ios#138]
Crash happens inside `ENXMLWriter.m:227` when the html contains a tag without a value.
In my case this was caused due to a html like this:
`<html><body bgcolor"#FFFFFF" link="#0066CC">`
I don‘t have control over the html that I'm trying to convert to ENML. The ENHTMLtoENMLConverter should though work even with malformed html.

I've submitted a PR (#137) which fixes this issue. Creating an issue here in case somebody else encounters this.

**Comment by akhaku** [comment]
Thanks, merged
