### ISSUE TITLE
Unable to install SDK using CocoaPods

### ISSUE THREAD

**Issue by xinatanil** [evernote/evernote-cloud-sdk-ios#143]
Creating a new project, and trying to install SDK using CocoaPods 1.2.0 gives me the following error.
```
[!] Unable to satisfy the following requirements:

- `evernote-cloud-sdk-ios (~> 3.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `evernote-cloud-sdk-ios (~> 3.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

Running `pod repo update` doesn't help.

**Comment by imougy** [comment]
I am confirming the issue.
Thank you @xinatanil, we will look into it.

**Comment by D-32** [comment]
@xinatanil @imougy 
As noted in #140 somebody from Evernote has to update the old pod & submit the new one to the cocoapods trunk.
In the meantime I suggest you do this in your pod file:
`pod 'evernote-cloud-sdk-ios', :git => 'https://github.com/evernote/evernote-cloud-sdk-ios.git'`

**Comment by xinatanil** [comment]
@D-32 Thanks, but installing pod this way still gives me 2.0.6 version :(.

**Comment by D-32** [comment]
@xinatanil sorry, it seems the readme is wrong. To get 3.0.x you have to use 'EvernoteSDK' as the pod name.

**Comment by xinatanil** [comment]
@D-32 trying to install `pod 'EvernoteSDK' ` gives me the following error `[!] Unable to find a specification for `EvernoteSDK``. Is it the way it's supposed to be right now?

**Comment by D-32** [comment]
@xinatanil You still have to specify the url like mentioned in my first comment, because the pod EvernoteSDK is not published. So you need to tell cocoapods where it can find it.

**Comment by xinatanil** [comment]
@D-32 Thanks! Now it works as expected.
For those who encounter the same issue and are too lazy to type, you can just copy this `pod 'EvernoteSDK', :git => 'https://github.com/evernote/evernote-cloud-sdk-ios.git'`

**Comment by imougy** [comment]
@xinatanil, now everything works as expected, you can just use `pod 'EvernoteSDK', '~> 3.0'` to get things working again.
