### ISSUE TITLE
The authenticate webview has no response

### ISSUE THREAD

**Issue by dawnnnnn** [evernote/evernote-cloud-sdk-ios#147]
I install sdk by cocoapods. follow command:

`pod 'EvernoteSDK', '~> 3.0.0'`

and I read the [Getting Started Guide](https://github.com/evernote/evernote-cloud-sdk-ios/blob/master/Getting_Started.md)

but in my project, it has some problems:

when I update a new version app, the user will reauthenticate the account in WebView. And it has no response that clicking the 'reauthenticate' button. 
if I install 'Evernote' app, there is no problem. Not all user will install 'Evernote' app, so it affects the use of the SDK.

Anyone help me ?

**Comment by siuying** [comment]
I had same problem. In fact even if I installed Evernote app I cannot authenticate the app. This make third party app totally unusable.

**Comment by imougy** [comment]
Do you still have this issue?
We are aware of this [issue 149](https://github.com/evernote/evernote-cloud-sdk-ios/issues/149).
