### ISSUE TITLE
Authentication not working on iOS 11 (iPhone)

### ISSUE THREAD

**Issue by siuying** [evernote/evernote-cloud-sdk-ios#148]
On iOS 11 using iPhone, if user try to authenticate Evernote via ``[ENSession authenticateWithViewController:preferRegistration:completion:]``, it would always failed immediately with an error with error code `ENErrorCodeCancelled`.

I believe this is related to a [bug of iOS 11](http://www.openradar.me/33153062), where an extra ``UIApplicationDidBecomeActiveNotification`` is sent when the device is **resign** active. This cause ``[ENOAuthAuthenticator handleDidBecomeActive]`` being trigger and caused the login always failed.

I added a workaround for this bug here: https://github.com/siuying/evernote-cloud-sdk-ios/commit/5d37b06398a2f1224db9f77679657f0a79428e7e

Unfortunately this only fix login issue on iPhone and we still noticed a different error on iPad.

**Comment by imougy** [comment]
I think this is related to [this issue 149](https://github.com/evernote/evernote-cloud-sdk-ios/issues/149)
