### ISSUE TITLE
Auth in Evernote app broken?

### ISSUE THREAD

**Issue by rolandpersson** [evernote/evernote-cloud-sdk-ios#149]
The functionality that authorises by switching to the Evernote app appears to be broken. Probably because of a bug in the Evernote app?

The app switch happens but inside the Evernote app the option to grant access is never displayed. This happens for two apps that I have been working on and the same thing also happens with other apps such as Scanbot. The Evernote app is launched but then nothing more happens.

I have tried on iOS 9 and iOS 10. Evernote app version is 8.3.356604

**Comment by alexandrhotko** [comment]
+1 (8.3.356604)

**Comment by imougy** [comment]
We are confirming the issue. Thanks for the heads up.

**Comment by imougy** [comment]
The issue is fixed in the next App Store update.
Thanks for the heads up.

**Comment by imougy** [comment]
@rolandpersson is your issue fixed now?

**Comment by rolandpersson** [comment]
@imougy Well, not really. Using Evernote 8.4.357715 the UI with the "Re-authorize" button appears. When pressing that button the web page reloads inside the Evernote app and asks for username and password. By filling in the username and password the authentication finally succeeds.

But the whole point of this is to not have to enter the username and password since I'm already logged in to the Evernote app... At least now it is possible to authenticate but I hope this feature is restored fully in the next release. Otherwise it makes more sense to just show the web view inside my app.

**Comment by imougy** [comment]
Totally agree. It was fixed when I wrote the previous comment (as you expect, no need to re-authenticate). Will see if this is a server issue or iOS related.

**Comment by imougy** [comment]
I am confirming that the next update will have the fix. 8.5.
Thanks for raising the issue.

**Comment by imougy** [comment]
Have you checked 8.5? It should fix the issue. Let me know so I can close it.
Thanks,

**Comment by imougy** [comment]
@rolandpersson is your issue fixed now?

**Comment by rolandpersson** [comment]
It is working now, thanks!
