### ISSUE TITLE
Can the SDK be used without using it's authentication flow?

### ISSUE THREAD

**Issue by agiletortoise** [evernote/evernote-cloud-sdk-ios#153]
If I have obtained a valid Evernote token via my own custom OAuth process, can I instantiate ENSessions and use the SDK without using it's authentication flow-methods?

I would like to maintain a consistent OAuth experience with other services in my app, and possibly support multiple Evernote accounts, while still taking advantage of the SDKs methods to work with the API.

I'm imagining a method that instantiates an ENSession with consumer key, secret and a known OAuth token...but if it exists, I could not find it.

Thanks for the help!

**Comment by imougy** [comment]
Have a look at ENOAuthAuthenticator.m. I am sure you can but it might need some work.

**Comment by agiletortoise** [comment]
Thanks, I'll take a look.
