### ISSUE TITLE
How can i straightly to find specified one EDAMNote/ENNote?

### ISSUE THREAD

**Issue by yiwangwuqian** [evernote/evernote-cloud-sdk-ios#165]
I just need record note for my reading book,how can i repeatedly update this one note programmatically(point to a particular note in the Evernote service)?

**Comment by imougy** [comment]
I tag the note with something and then search and get it back.  Of course you can get a list of notes.
Here is my code:-
- (void) findNotesWithSymbol:(NSString*)symbol completion:(ENSessionFindNotesCompletionHandler)completion{
	NSString *searchNotation = [NSString stringWithFormat:@"tag:%@" , symbol];
	[self findNotesWithSearchNotation:searchNotation completion:completion];
}

- (void) findNotesWithSearchNotation:(NSString*)searchNotation completion:(ENSessionFindNotesCompletionHandler)completion{
	ENNoteSearch *noteSearch = [ENNoteSearch noteSearchWithSearchString:searchNotation];
	[[ENSession sharedSession] findNotesWithSearch:noteSearch inNotebook:self.stocksLiveNoteBook orScope:ENSessionSearchScopePersonal sortOrder:ENSessionSortOrderRecentlyCreated maxResults:0 completion:^(NSArray *findNotesResults, NSError *findNotesError) {
		completion(findNotesResults, findNotesError);
	}];
}

**Comment by yiwangwuqian** [comment]
Thanks for your answer!!! I get the point now.
I have another question:What's the max count of tags created by me?Or there's no limits?

> I tag the note with something and then search and get it back. Of course you can get a list of notes.
> Here is my code:-
> 
> * (void) findNotesWithSymbol:(NSString*)symbol completion:(ENSessionFindNotesCompletionHandler)completion{
>   NSString *searchNotation = [NSString stringWithFormat:@"tag:%@" , symbol];
>   [self findNotesWithSearchNotation:searchNotation completion:completion];
>   }
> * (void) findNotesWithSearchNotation:(NSString*)searchNotation completion:(ENSessionFindNotesCompletionHandler)completion{
>   ENNoteSearch *noteSearch = [ENNoteSearch noteSearchWithSearchString:searchNotation];
>   [[ENSession sharedSession] findNotesWithSearch:noteSearch inNotebook:self.stocksLiveNoteBook orScope:ENSessionSearchScopePersonal sortOrder:ENSessionSortOrderRecentlyCreated maxResults:0 completion:^(NSArray *findNotesResults, NSError *findNotesError) {
>   completion(findNotesResults, findNotesError);
>   }];
>   }

Thanks for your answer!!! I get the point now.
I have another question:What's the max count of tags created by me?Or there's no limits?

**Comment by yiwangwuqian** [comment]
> I tag the note with something and then search and get it back. Of course you can get a list of notes.
> Here is my code:-
> 
> * (void) findNotesWithSymbol:(NSString*)symbol completion:(ENSessionFindNotesCompletionHandler)completion{
>   NSString *searchNotation = [NSString stringWithFormat:@"tag:%@" , symbol];
>   [self findNotesWithSearchNotation:searchNotation completion:completion];
>   }
> * (void) findNotesWithSearchNotation:(NSString*)searchNotation completion:(ENSessionFindNotesCompletionHandler)completion{
>   ENNoteSearch *noteSearch = [ENNoteSearch noteSearchWithSearchString:searchNotation];
>   [[ENSession sharedSession] findNotesWithSearch:noteSearch inNotebook:self.stocksLiveNoteBook orScope:ENSessionSearchScopePersonal sortOrder:ENSessionSortOrderRecentlyCreated maxResults:0 completion:^(NSArray *findNotesResults, NSError *findNotesError) {
>   completion(findNotesResults, findNotesError);
>   }];
>   }

Thanks for your answer!!! I get the point now.
I have another question:What's the max count of tags created by me?Or there's no limits?

**Comment by imougy** [comment]
There is no limit.  I have very deep integration with my app (Stocks Live on the App Store) and I tag almost 4000 stocks and Evernote is a beast, can handle everything.
Good luck, what is your app?

**Comment by mpnow** [comment]
Actually there are limits to the number of tags in an account.  You can see all of Evernote's limits in the "Limits" section here: [http://dev.evernote.com/doc/reference/](http://dev.evernote.com/doc/reference/)

**Comment by imougy** [comment]
> Actually there are limits to the number of tags in an account. You can see all of Evernote's limits in the "Limits" section here: http://dev.evernote.com/doc/reference/

That is max tag inside one note, if that is the concern, but there is no tag limits for the general service, meaning, if I create a tag per note, this will pass fine, which is a way to find a note like in my previous answer.
Thanks for the heads up btw.

**Comment by mpnow** [comment]
Actually there is a limit for the general service - as of this writing it's 100,000 tags per account.  That's a large number, granted, but to be accurate it's not unlimited tags.

**Comment by yiwangwuqian** [comment]
> > Actually there are limits to the number of tags in an account. You can see all of Evernote's limits in the "Limits" section here: http://dev.evernote.com/doc/reference/
> 
> That is max tag inside one note, if that is the concern, but there is no tag limits for the general service, meaning, if I create a tag per note, this will pass fine, which is a way to find a note like in my previous answer.
> Thanks for the heads up btw.

Thanks for your reply!
Here's our app link:https://apps.apple.com/cn/app/%E6%8E%8C%E9%98%85%E7%B2%BE%E9%80%89/id1447341012

**Comment by yiwangwuqian** [comment]
> Actually there is a limit for the general service - as of this writing it's 100,000 tags per account. That's a large number, granted, but to be accurate it's not unlimited tags.

Thank you so much!
I think i get the useful information here.
