### ISSUE TITLE
OAuth first step always get 401 statusCode

### ISSUE THREAD

**Issue by yiwangwuqian** [evernote/evernote-cloud-sdk-ios#166]
Now i debug by the developer token.
But i need to switch call method:
[ENSession setSharedSessionConsumerKey:consumerSecret:optionalHost:],and  always get 401 statusCode,how to make it work?

**Comment by imougy** [comment]
This is what I call to setup the SDK, you should use your own keys
- (void) setupEvernoteSDK{
    [ENSession setSharedSessionConsumerKey:EVERNOTE_CONSUMER_KEY
                            consumerSecret:EVERNOTE_CONSUMER_SECRET
                              optionalHost:nil];
}
There is no error after calling this method. When do you get error?

**Comment by yiwangwuqian** [comment]
Now i found evernote's developer fix this issue:
https://github.com/yinxiang-dev/evernote-cloud-sdk-ios/commit/6575c2b2309d313efa53297affb48f7e0645cb12

**Comment by imougy** [comment]
Awesome!
Did you communicate with someone at Evernote? Or how did they hear about it?

**Comment by yiwangwuqian** [comment]
> Awesome!
> Did you communicate with someone at Evernote? Or how did they hear about it?

I sent them a few emails about OAuth.

**Comment by Gargo** [comment]
@yiwangwuqian I have installed your last commit with cocoapods but it still gives 401 error

**Comment by yiwangwuqian** [comment]
> @yiwangwuqian I have installed your last commit with cocoapods but it still gives 401 error

I think maybe country difference，you could directly connect Evernote's developer。
