### ISSUE TITLE
Login view stopped showing password input recently.

### ISSUE THREAD

**Issue by umekun123** [evernote/evernote-cloud-sdk-ios#176]
## Repro steps

- Try to login with Evernote (ENSession.shared.authenticate(with:preferRegistration:completion:))
- A login view controller is presented by the Evernote SDK
- Input your email, then tap on Continue
- It used to show the password form before, but now it turns into the white screen.

Does anyone have the same issue?

![IMG_2261](https://user-images.githubusercontent.com/614288/85209529-bf480300-b373-11ea-85a2-2799b5d44471.PNG)
![IMG_2262](https://user-images.githubusercontent.com/614288/85209530-c111c680-b373-11ea-821a-f10b5b39fdf4.PNG)

**Comment by michi10560** [comment]
I have the same problem as you do.

There is the issue on iOS 13.5.1
But there is not the issue  on iOS 12.4.6.
I can login on iOS 12.4.6.

**Comment by umekun123** [comment]
Thanks for the info, I really hope the Evernote team could fix the issue or provide some workaround.

**Comment by zonabi** [comment]
Engineer at Evernote here.  Thank you for the report.  We are currently investigating the blank login screen issue.  We do not currently have a workaround.

**Comment by umekun123** [comment]
Thank you very much for investigating this, I really hope it will be fixed.

**Comment by umekun123** [comment]
I found that the issue has been fixed on my app today, maybe they fixed it?

**Comment by zonabi** [comment]
Yes, the issue has been fixed as of today.  Please do let us know if you still experience problems.

Do note that Google sign in is known as not working in our iOS SDK

**Comment by umekun123** [comment]
Thank you very much!

**Comment by imougy** [comment]
Thank you @zonabi.  Please note, there is an easy merge for getting rid or UIWebView in favor of WKWebView.  Issue #170 .
Greetings to the Austin team please.
Cheers

**Comment by markfoden** [comment]
I have got this issue today

**Comment by zonabi** [comment]
We have reports this issue has came back, and we have verified its regressed and are looking into it.
