### ISSUE TITLE
Method fails:  getResourceByHashWithGuid:contentHash:withData:withRecognition:withAlternateData:success:failure

### ISSUE THREAD

**Issue by srjohnson** [evernote/evernote-cloud-sdk-ios#31]
getResourceByHashWithGuid:contentHash:withData:withRecognition:withAlternateData:success:failure
This method fails with type mismatches for fields 8 and 11.  See attached screenshot.  This method worked in the old SDK.
![enerror2-2](https://cloud.githubusercontent.com/assets/8525018/4013869/e59e51dc-2a1a-11e4-8b71-fca2a571694e.png)

**Comment by everic** [comment]
With https://github.com/evernote/evernote-cloud-sdk-ios/commit/d100ebd0616e62baede3b59f69d59cc062bafbf8
You can see from the sample app how you can download all the resources in a note. I verified with personal, shared and business notebooks. Thank you!
