### ISSUE TITLE
getFilteredSyncChunkAfterUSN: doesn't always give the updated information

### ISSUE THREAD

**Issue by srjohnson** [evernote/evernote-cloud-sdk-ios#33]
Sometimes the received SyncChunk has all the fields set to nil, even though there are updates.

Here is the code that checks the sync state and requests the SyncChunk:
    NSLog(@"user data getting personal sync state");
    [[[ENSession sharedSession] primaryNoteStore] getSyncStateWithSuccess:^(EDAMSyncState *syncState) {
        NSLog(@"got personal sync state");
        NSInteger lastUpdateCount = [self.personalSyncState.updateCount integerValue];
        if (!self.personalSyncState) {
            lastUpdateCount = [syncState.updateCount integerValue];
        }
        NSLog(@"personal sync chunk lastUpdateCount %d, newUpdateCount %d",lastUpdateCount, [syncState.updateCount integerValue]);
        BOOL shouldUpdate = [syncState.updateCount integerValue] > lastUpdateCount;
        self.personalSyncState = syncState;
        if (shouldUpdate) {
            EDAMSyncChunkFilter *filter = [self createChunkFilter];
            [[[ENSession sharedSession]primaryNoteStore]getFilteredSyncChunkAfterUSN:lastUpdateCount maxEntries:150 filter: filter success:^(EDAMSyncChunk *syncChunk) {
                NSLog(@"personal chunk %@",[syncChunk debugDescription]);
                [self sendNotification:kMMMEvernotePersonalChunkCollected chunk:syncChunk error:nil];
            } failure:^(NSError *error) {
                self.lastEvernoteError = error;
                [self sendNotification:kMMMEvernotePersonalChunkCollected chunk:nil error:error];
            }];
        } else {
            [self sendNotification:kMMMEvernotePersonalChunkCollected chunk:nil error:nil];
        }
    } failure:^(NSError *error) {
        self.collectedPersonalInformation = YES;
        [self setError:error];
        [self sendNotification:kMMMEvernotePersonalChunkCollected chunk:nil error:error];
        ;
    }];

Here is the log showing the updateCounts and the returned SyncChunk:
2014-08-25 21:57:26.009 got personal sync state
2014-08-25 21:57:26.009 personal sync chunk lastUpdateCount 377, newUpdateCount 392
2014-08-25 21:57:26.126  personal chunk EDAMSyncChunk: 0x14ec6b40; currentTime = 1409021844038; chunkHighUSN = 392; updateCount = 392; notes = (null); notebooks = (null); tags = (null); searches = (null); resources = (null); expungedNotes = (null); expungedNotebooks = (null); expungedTags = (null); expungedSearches = (null); linkedNotebooks = (null); expungedLinkedNotebooks = (null);

Here is the SyncChunkFilter:
    EDAMSyncChunkFilter *filter = [[EDAMSyncChunkFilter alloc]init];
    filter.includeNotes = @(YES);
    filter.includeNoteAttributes = @(YES);
    filter.includeNoteResources = @(NO);
    filter.includeNotebooks = @(YES);
    filter.includeTags = @(NO);
    filter.includeSearches = @(NO);
    filter.includeResources = @(NO);
    filter.includeLinkedNotebooks = @(YES);
    filter.includeExpunged = @(YES);
    filter.includeNoteApplicationDataFullMap = @(YES);
    filter.includeNoteResourceApplicationDataFullMap = @(NO);
    filter.includeResourceApplicationDataFullMap = @(NO);
    filter.requireNoteContentClass = @"XXXXXX";
    return filter;

Here is the log for a successful sync chunk query in the same session:

2014-08-25 21:53:30.370 got personal sync state
2014-08-25 21:53:30.371  personal sync chunk lastUpdateCount 358, newUpdateCount 359
2014-08-25 21:53:30.515  personal chunk EDAMSyncChunk: 0x14dcf3b0; currentTime = 1409021608405; chunkHighUSN = 359; updateCount = 359; notes = (null); notebooks = (
    "EDAMNotebook: 0x14dbfb80; guid = 6a62a30c-51d8-46f5-a07c-b598a3c4bbfc; name = sync test 2; updateSequenceNum = 359; defaultNotebook = 0; serviceCreated = 1409021590000; serviceUpdated = 1409021590000; publishing = (null); published = (null); stack = (null); sharedNotebookIds = (null); sharedNotebooks = (null); businessNotebook = (null); contact = (null); restrictions = EDAMNotebookRestrictions: 0x14dfa880; noReadNotes = (null); noCreateNotes = (null); noUpdateNotes = (null); noExpungeNotes = 1; noShareNotes = (null); noEmailNotes = 1; noSendMessageToRecipients = (null); noUpdateNotebook = (null); noExpungeNotebook = 1; noSetDefaultNotebook = (null); noSetNotebookStack = (null); noPublishToPublic = (null); noPublishToBusinessLibrary = (null); noCreateTags = (null); noUpdateTags = (null); noExpungeTags = 1; noSetParentTag = (null); noCreateSharedNotebooks = (null); updateWhichSharedNotebookRestrictions = (null); expungeWhichSharedNotebookRestrictions = 2; noShareNotesWithBusiness = 1;"
); tags = (null); searches = (null); resources = (null); expungedNotes = (null); expungedNotebooks = (null); expungedTags = (null); expungedSearches = (null); linkedNotebooks = (null); expungedLinkedNotebooks = (null);

**Comment by everic** [comment]
No response from reporter in two months. Closing this bug.
