### ISSUE TITLE
Note attachments not listing correctly in Evernote for Business integration

### ISSUE THREAD

**Issue by sunilpatro** [evernote/evernote-cloud-sdk-ios#35]
Hi,

I have been in touch with Matt Caroll and he suggested we report this bug here. The issue details are below.

We integrated Evernote for Business functionality by integrating the Evernote SDK 2.0. The adhoc build can be installed from testflight below.
https://testflightapp.com/install/8cc38f2189895fdb9a818c06d4ae8c87-MTI1NzY2MjQ/

Our basic functionality is that we want to list the attachments saved in Evernote for personal and business notebooks. While testing it, we found some issues that we need your help in troubleshooting.

- In a business shared notebook, I have one file attached. But the Evernote search query returns two results with the same file name.
- In a personal shared notebook,  we are getting zero search results even if there are notes with attachments.

I have attached the screenshots for your reference. 
![evernote_notebook2_attachment_list](https://cloud.githubusercontent.com/assets/7921045/4055560/7f139d42-2da7-11e4-9666-3cbfac10a105.png)
![evernote_notebook1_attachment_list](https://cloud.githubusercontent.com/assets/7921045/4055561/7f1c2d18-2da7-11e4-8645-07a7430eb632.png)
![evernote_notebook_list](https://cloud.githubusercontent.com/assets/7921045/4055562/7f1f1df2-2da7-11e4-8855-09f0cad17d5c.png)

The code we are using to get list of notes with file attachments in a Notebook.

[[ENSession sharedSession] findNotesWithSearch:[ENNoteSearch noteSearchWithSearchString:@"any: resource:application/* resource:image/*"]

                                        inNotebook:notebook

                                           orScope:nil

                                         sortOrder:ENSessionSortOrderRelevance

                                        maxResults:0

                                        completion:^(NSArray *findNotesResults, NSError *findNotesError) {

                                        if (findNotesError) {

                                            if (block) {

                                            block(nil, findNotesError);

                                            }

                                        } else if (findNotesResults.count) {

                                            [SEEvernoteHelper getNoteMetaDataFromResultList:findNotesResults onCompletion:block];

                                        } else {

                                            if (block) {

                                            block(nil, nil);

                                            }

                                        }

                                    }];

**Comment by everic** [comment]
Hi @sunilpatro 
I just pushed https://github.com/evernote/evernote-cloud-sdk-ios/commit/d100ebd0616e62baede3b59f69d59cc062bafbf8
With this, you can try the sample app to see how you can list the resources in a note. I verified with all kinds of notebooks, personal, personal shared & business. All of them works fine without issue.

Closing this bug.
