### ISSUE TITLE
Creating Business Notebook doesn't create corresponding LinkedNotebook

### ISSUE THREAD

**Issue by kwenglish32** [evernote/evernote-cloud-sdk-ios#37]
When creating a Business Notebook, the old SDK created the corresponding linked notebook so the user didn't have to go into Evernote and join to the notebook.  This new SDK doesn't have that functionality.

Here's what the old SDK had which appears to be missing in the new SDK:

(void)createBusinessNotebook:(EDAMNotebook *)notebook
               success:(void(^)(EDAMLinkedNotebook *notebook))success
                       failure:(void(^)(NSError *error))failure {
    EvernoteNoteStore* businessNoteStore = [EvernoteNoteStore businessNoteStore];
    [businessNoteStore createNotebook:notebook success:^(EDAMNotebook *businessNotebook) {
        EDAMSharedNotebook* sharedNotebook = businessNotebook.sharedNotebooks[0];
        EDAMLinkedNotebook* linkedNotebook = [[EDAMLinkedNotebook alloc] init];
        [linkedNotebook setShareKey:[sharedNotebook shareKey]];
        [linkedNotebook setShareName:[businessNotebook name]];
        [linkedNotebook setUsername:[[[EvernoteSession sharedSession] businessUser] username]];
        [linkedNotebook setShardId:[[[EvernoteSession sharedSession] businessUser] shardId]];
        [self createLinkedNotebook:linkedNotebook
                           success:^(EDAMLinkedNotebook *businessLinkedNotebook) {
                               success(businessLinkedNotebook);
        } failure:^(NSError *error) {
            failure(error);
        }];
    } failure:^(NSError *error) {
        failure(error);
    }];
}

**Comment by everic** [comment]
fixed in https://github.com/evernote/evernote-cloud-sdk-ios/commit/93e658b987b1a2444c39b42cafed59e5394de2a5
