### ISSUE TITLE
Resources should not be loaded from main bundle

### ISSUE THREAD

**Issue by agiletortoise** [evernote/evernote-cloud-sdk-ios#53]
In serveral places, the SDK loads resources with calls to:

[NSBundle mainBundle]

This breaks and crashes if the ENSDK is included in an iOS Framework instead of the main project.

Recommend replacing these calls with calls to [NSBundle bundleWithClass:] or other more portable call.

**Comment by everic** [comment]
Should be fixed by https://github.com/evernote/evernote-cloud-sdk-ios/commit/5e3316ced4ec8ae3a863f1fa2b902113d0a991c1
