### ISSUE TITLE
Tags in ENSaveToEvernoteViewController are hard to delete

### ISSUE THREAD

**Issue by an0** [evernote/evernote-cloud-sdk-ios#62]
I know overwriting after selecting a tag can delete it. But it is very undiscoverable by users. Deleting backward in text field should be able to delete the preceding tag directly. At least, tapping delete key after selecting a tag should delete the tag.

**Comment by everic** [comment]
Should be fixed by https://github.com/evernote/evernote-cloud-sdk-ios/commit/116e4850ae2e2f182869bfc5dbcef4980b1db66d
