### ISSUE TITLE
Better error description for ENErrorCode

### ISSUE THREAD

**Issue by Constantine-Fry** [evernote/evernote-cloud-sdk-ios#66]
Would be nice to have localised description passed in userInfo to show in error alert. Errors like `ENErrorCodeLimitReached`, `ENErrorCodeQuotaReached` definitely should have some meaningful description for user. Otherwise when one uses `error.localizedDescription` it returns (ENErrorDomain error X.)

**Comment by everic** [comment]
Fixed by https://github.com/evernote/evernote-cloud-sdk-ios/commit/0ac83243747bbf035dfe57ae5a8962143d326ac3
