### ISSUE TITLE
Issue with UI for selecting notebook, title, tags

### ISSUE THREAD

**Issue by ranjitk-plackal** [evernote/evernote-cloud-sdk-ios#67]
![img_0038](https://cloud.githubusercontent.com/assets/981003/5281601/0b89e856-7b25-11e4-8c88-2c32232b9817.PNG)

As it can be seen in the above image the text I want to share is not shown fully in the note body. I think it is a layout issue.

Hoping to be resolved it soon.

Thanks

**Comment by everic** [comment]
Only happens when you have a really long word(more than 40) without space. Does not happen in real life. Works fine for normal cases. Not going to fix.
![screen shot 2015-01-26 at 7 06 37 pm](https://cloud.githubusercontent.com/assets/7154385/5912831/a8ffdd5a-a58e-11e4-9371-18b97f603a0b.png)
