### ISSUE TITLE
Swift programming Language tutorials needed

### ISSUE THREAD

**Issue by Beck-Sisyphus** [evernote/evernote-cloud-sdk-ios#69]
Hi Evernote developer,

It will be great if you can come out with an Evernote SDK using Swift programming language. It takes me a long time to mix the Objective-C with Swift.

Thanks!

**Comment by everic** [comment]
Yeah, in general mixing Objective-C and Swift is tricky. It's definitely on the roadmap that I'll developer a Swift SDK, but the schedule is TBD. Closing this ticket for now.
