### ISSUE TITLE
Shared Authentication with App Extension

### ISSUE THREAD

**Issue by siuying** [evernote/evernote-cloud-sdk-ios#72]
My app support App Extensions (Share/Action). In the main app user already logged in and the extension should just use the auth token from the main app.

To enable this, I'd need to enable shared key chain. Currently Evernote SDK did not expose ``ENCredentials``, ``ENCredentialStore`` and ``ENSSKeychain``. Which make configure the key chain outside impossible.

Also, ``ENSSKeychain`` seems to be an older vendored version of ``SSKeychain``. Newer versions of ``SSKeychain`` support configuring the App group by using ``SSKeychainQuery``.

This probably a common scenario (as seen in #65). I'd love to send a PR to fix this. However I'm not sure where should I get started. Your input is greatly appreciated.

**Comment by siuying** [comment]
I've [made a patch](https://github.com/siuying/evernote-cloud-sdk-ios/commit/5de7f20f04542154e7fe1c4ee4a7236ac2266f10) to implement this. If this could be merge please tell me, I'd love to send a PR.

**Comment by siuying** [comment]
I've [made a patch](https://github.com/siuying/evernote-cloud-sdk-ios/compare/evernote:master...shared-container) that do following:

- method to configure App Group from ``ENSession``
- method to configure Keychain group from ``ENSession``
- options to create ``ENPreferenceStore`` under shared container path
- modify ``ENSSKeychain`` to set access group based on keychain group

Update and use latest ``SSKeychain`` is probably better, but these changes make extensions work for me.

**Comment by everic** [comment]
@siuying Your patch looks good. One question, is there any reason that you made changes to the project file? I'm updating the project to use CocoaTouch frameworks in iOS 8 and going to make it a CocoaPod pod, so I guess updating the SSKeychain will be easier.

**Comment by siuying** [comment]
There is no reason I made changes to project file, maybe its Xcode.

Look forward to see the CocoaPods change!

**Comment by everic** [comment]
I'll update the project in a few hours and it should contain the latest SSKeychain, with cocoapod. Please make a new patch or a pull request. Thank you.

**Comment by siuying** [comment]
Certainly! Thanks.

**Comment by everic** [comment]
@siuying I just updated the project with cocoapod. It should contains the latest SSKeychain. Let me know if it works for you.

**Comment by siuying** [comment]
Added in #76

**Comment by everic** [comment]
Closing this bug as the pull request is merged. Thank you.
