### ISSUE TITLE
Error getting password from keychain: Error Domain=com.samsoffes.sskeychain Code=-25308 "The operation couldn’t be completed. (com.samsoffes.sskeychain error -25308.)"

### ISSUE THREAD

**Issue by crarau** [evernote/evernote-cloud-sdk-ios#75]
Randomly the cloud sdk fails to get the authentication token.

The error received is: 
**Error getting password from keychain: Error Domain=com.samsoffes.sskeychain Code=-25308 "The operation couldn’t be completed. (com.samsoffes.sskeychain error -25308.)"**

A few notes:
* the vast majority there are no problems getting the authentication token.
* the error appears right after the application is started
* the consumer key is put in the AppDelegate on top: [ENSession setSharedSessionConsumerKey:@"..." consumerSecret:@"..." optionalHost:nil];

Please advice.
Thanks, 
Ciprian.

Here are the logs from one of the instances.

**At 12:20 the token is valid:**

2015-01-21T12:20:26.786-0500,[ENCredentialStore credentialsForHost:][line:67,current credentials ENCredentials host: www.evernote.com, user:294536 notestore:https://www.evernote.com/shard/s4/notestore apiurl:https://www.evernote.com/shard/s4/, autenticationToken:S=s4:U=47e88:E=15264d94b90……., expirationdate:2016-01-21 15:41:48 +0000

**At 12:43 the application is started again, this time reading the authentication token is returning an error:**

*2015-01-21T12:43:23.602-0500,[AppDelegate application:didFinishLaunchingWithOptions:][line:75]MAIN_THREAD,Application BOOSTRAP*
2015-01-21T12:43:23.608-0500,[AppDelegate application:didFinishLaunchingWithOptions:][line:77]MAIN_THREAD,Evernote boostrap
....
2015-01-21T12:43:27.282-0500,[ENCredentials authenticationToken][line:100]BACK,-[ENCredentials authenticationToken] [Line 100] Error getting password from keychain: Error Domain=com.samsoffes.sskeychain Code=-25308 "The operation couldn’t be completed. (com.samsoffes.sskeychain error -25308.)"

2015-01-21T12:43:27.435-0500,[ENCredentialStore credentialsForHost:][line:67]BACK,current credentials ENCredentials host: www.evernote.com, user:294536 notestore:https://www.evernote.com/shard/s4/notestore apiurl:https://www.evernote.com/shard/s4/, autenticationToken:(null), expirationdate:2016-01-21 15:41:48 +0000

2015-01-21T12:43:27.476-0500,[ENCredentials authenticationToken][line:100]BACK,-[ENCredentials authenticationToken] [Line 100] Error getting password from keychain: Error Domain=com.samsoffes.sskeychain Code=-25308 "The operation couldn’t be completed. (com.samsoffes.sskeychain error -25308.)"

2015-01-21T12:43:27.533-0500,[ENCredentials authenticationToken][line:100]BACK,-[ENCredentials authenticationToken] [Line 100] Error getting password from keychain: Error Domain=com.samsoffes.sskeychain Code=-25308 "The operation couldn’t be completed. (com.samsoffes.sskeychain error -25308.)"
v2.0.1,crarau,Info,2015-01-21T12:43:27.613-0500,[ENCredentialStore removeCredentials:][line:77]BACK,Remove the credential ENCredentials host: www.evernote.com, user:294536 notestore:https://www.evernote.com/shard/s4/notestore apiurl:https://www.evernote.com/shard/s4/, autenticationToken:(null), expirationdate:2016-01-21 15:41:48 +0000 from (
     0   IdeaPlaces                          0x00000001001831c4 -[ENCredentialStore removeCredentials:] + 152
     1   IdeaPlaces                          0x00000001001830d4 -[ENCredentialStore credentialsForHost:] + 568
     2   IdeaPlaces                          0x00000001001c39a8 -[ENSession credentialsForHost:] + 100
     3   IdeaPlaces                          0x00000001001af9b4 -[ENSession startup] + 684
     4   IdeaPlaces                          0x00000001001af634 -[ENSession init] + 260
     5   IdeaPlaces                          0x00000001001af260 __26+[ENSession sharedSession]_block_invoke + 84
     6   IdeaPlaces                          0x000000010035b6e8 __NR__dispatch_once_block_invoke + 48
     7   libdispatch.dylib                   0x0000000194a9d36c <redacted> + 16
     8   libdispatch.dylib                   0x0000000194a9e244 dispatch_once_f + 96
     9   IdeaPlaces                          0x000000010035b6b0 NR__dispatch_once + 220
     10  IdeaPlaces                          0x00000001001af1f8 +[ENSession sharedSession] + 36
….
….
….

**Comment by crarau** [comment]
I've found a few tracks for the issue and a possible cause:

1. http://stackoverflow.com/questions/9723949/ios-sfhfkeychainutils-failing-sometimes-with-error-25308-errsecinteractionnot
Similar to this post, my iPhone also has a password lock and my app is allowed to run in background for the location based reminders. 
The authentication token issue usually happens after I open the app from the push notification with the iOS lock ON, but cannot guarantee it's the only case.

2.From Apple (http://lists.apple.com/archives/apple-cdsa/2007/Oct/msg00019.html)
Certificate, Key, and Trust Services Reference
errSecInteractionNotAllowed | –25308 | Interaction with the user is required in order to grant access or process a request; however, user interaction with the Security Server has been disabled by the program.

3. Also found a similar issue that the Hockey App used to have:
http://support.hockeyapp.net/discussions/problems/20813-ios-app-keeps-asking-me-to-authorize-hockeyapp

The steps to reproduce are similar to mine:
1. The app is woken up in the background.
2. The iPhone has a lock, requiring the user interaction
If the keychain is accessed during this time the call will result in the error above.

Everything seem to point to the fact that the Evernote SDK is initialized while the app is in the background.
The authentication token fetch fails.
At that point the Evernote SDK clears all the authentication tokens.
After this the user has no choice but to re-authentication with Evernote.

Let me know what you think,
Thanks,
Ciprian.

**Comment by everic** [comment]
Hello @crarau 
Thank you for your detailed writeup

I submitted a fix https://github.com/evernote/evernote-cloud-sdk-ios/commit/78c5bf3f99b6145088fe2ddc594eb6583f3a1717
Hopefully can resolve this issue
http://stackoverflow.com/questions/20759169/cfuuid-stored-in-sskeychain-is-null-in-some-devices

Please see if it helps
I'm closing this bug now but feel free to reopen this if this still happens. Thank you.

**Comment by crarau** [comment]
@ everic Thanks for taking the time to investigate and fix.

That's exactly what I ended up doing myself (today), but I was not happy with the solution since it poses a security issue. Apple recommends against using Always since it defeats the purpose of the Security Chain. 
Apple recommends at most using: kSecAttrAccessibleAfterFirstUnlock see https://developer.apple.com/videos/wwdc/2013/#709 minute 25:30.
which is already good. But there is still a chance that the SDK tries to access the keychain before the first unlock and this case will have to be handled by making sure that the authentication token is not erased from the keychain.
I leave this for you to judge.
Kind regards,
Ciprian.

**Comment by crarau** [comment]
Here are some other articles that talk about the same issue.
Even though in both articles the solution was to use kSecAttrAccessibleAlways read the comments.

https://blog.loom.com/how-we-fixed-the-ios7-forced-logout-bug-thats-been-plaguing-so-many-apps/
http://stackoverflow.com/questions/10536859/ios-keychain-not-retrieving-values-from-background

Ciprian.

**Comment by everic** [comment]
@crarau Thank you for your information

I think in this situation, the fix is to ensure that we can read the authentication token from the keychain no matter what the state the device is in. This is very important as pretty much all the Evernote operations rely on the authentication to be there. I cannot think of any new security risk this one line of code changes adds. When the user authentication his or her account to a 3rd party, he already grants the access to the client, regardless of the state. And he or she may at anytime revoke the token from the security page setting in Evernote Web. So I think the fix is fine in terms of security concerns.

Plus, other developers cannot read the keychain as the apps are from different venders. For hackers, if they hacked the iOS keychain, then all the usernames and passwords are there, I don't think an auth token will matter in that case. :-)

**Comment by crarau** [comment]
@everic 

Here is some more information about the "hacking" dangers related to the iOS Keychain:

http://sit.sit.fraunhofer.de/studies/en/sc-iphone-passwords-faq.pdf
In section 2.1:
1. The Always protection class means that the entry is decryptable without user
interaction right after the device finished booting, the encryption is not tied
to the user passcode. These entries can easily be retrieved by an attacker.
2. On the other hand, AfterFirstUnlock requires the passcode and is decryptable after
a user unlocked the screen and entered his passcode after a device boot.
3. The third, passcode-dependent class WhenUnlocked is only readable while
the device is not locked.
.....
This means that in all these iOS versions the entries marked Always are vulnerable to an attacker
with physical access to the device.

-------
This being said IdeaPlaces is working super nicely with the "Always" setting being put in place. It was a very difficult issue to find.
Given that the authentication token can always be revoked from https://www.evernote.com/AuthorizedServices.action the current solution is secure enough.

Thanks,
Ciprian.
