### ISSUE TITLE
Exception when using [ENSession sharedSession] uploadNote with ENNotebook specified

### ISSUE THREAD

**Issue by ilia510** [evernote/evernote-cloud-sdk-ios#81]
Hello,

I am receiving the following exception.

Exception is:-[EDAMNotebook allowsWriting]: unrecognized selector sent to instance 0x7fac82e8d6f0

when using the following function:

            [[ENSession sharedSession] uploadNote:note notebook:weakSelf.selectedNotebook completion:^(ENNoteRef *noteRef, NSError *uploadNoteError) 

It was working correctly before.  selectedNotebook is a ENNotebook object. 

Maybe I should use another method to create a note?

**Comment by everic** [comment]
Hi @ilia510 
Can you try the sample app and go Save Activity->Share button->Save to Evernote in the bottom row and see if it works? It works for me without any issue and we're using the same uploadNote API. I suspect your weakSelf.selectedNotebook is a EDAMNotebook, which does not have the allowsWriting property. Can you check your code or paste the snippet where you set the selectedNotebook object?

Thank you.

**Comment by ilia510** [comment]
Yes, everic, you are absolutely right. I was send EDAMNotebook instead of ENNotebook. To get the notebooks list I was using primaryNoteStore method - listNotebooksWithSuccess, which returned me an array of EDAMNotebooks. Now switched to ENSession methods.

And here I have a question. How do I convert EDAMNotebook to ENNotebook in code? [ENNotebook alloc] initWithNotebook] is not available.

**Comment by everic** [comment]
@ilia510 Please use
```objective-c
[[ENSession sharedSession] listNotebooksWithCompletion: completion]
```
method

Thank you.
