### ISSUE TITLE
Note URL

### ISSUE THREAD

**Issue by agiletortoise** [evernote/evernote-cloud-sdk-ios#87]
After creating a note (e.g. with [ENSession:uploadNote:notebook:completion]) is there an easy way to grab or construct a URL reference to the created note?

Either a URL to open the note on the web, or in the Evernote app.

**Comment by everic** [comment]
You have two options:

1. If the note is for sharing purposes, you can use the ENNoteRef in your completion handler to call shareNote:noteRef completion:completion on your shared ENSession. And you will get a URL that everyone with that URL can view the note on the web. But keep in mind that you may only do this when the user explicitly choose to do so.

2. If you want to keep a URL reference to the Evernote app and not share the note, you can use an Evernote app link. Check out viewNoteInEvernote:noteRef function on ENSession to see how I construct the app link URL for the note. The app link should work with Evernote clients on other platforms (Windows, Mac, Android) as long as the app is installed.
