### ISSUE TITLE
ENSession Exception

### ISSUE THREAD

**Issue by rathnaum** [evernote/evernote-cloud-sdk-ios#88]
if (ENSession.SharedSession.IsAuthenticated == false)
            {
                ENSession.SharedSession.AuthenticateToEvernote();
            }
The above code is throughing NullReference exception. With developer token I did not see this issues and now planning to authenticate to EN using OAuth. Please help

**Comment by everic** [comment]
Is this pseudocode in your project? I don't have AuthenticateToEvernote API in the Evernote iOS SDK. Are you using Objective-C and this SDK?

Thank you.

**Comment by rathnaum** [comment]
Its for Windows, DotNet.
SDK mentions this API for authentication.For some reason it is not going through.
Sorry, I think I posted under IOS forum.
CheersRathna

Date: Fri, 27 Mar 2015 09:57:13 -0700

**Comment by everic** [comment]
Please file a bug on the Windows SDK repo https://github.com/evernote/evernote-cloud-sdk-windows

Thank you
