### ISSUE TITLE
Revoking access from web to my app and [ENSession isAuthenticated]

### ISSUE THREAD

**Issue by tettoffensive** [evernote/evernote-cloud-sdk-ios#90]
This is how I am authenticating for my iOS app, however, when I went to my account on the web and revoked access to my app `[ENSession isAuthentication]` still returns `YES`. Causing my app to crash because it thinks evernote is authenticated, but it is not when I try to read the notes.

```
- (void)authenticateSessionFromController:(id)controller block:(GDEvernoteAuthenticationBlock)block{
    __block BOOL authenticated;
    ENSession *session = [ENSession sharedSession];
    //If the session is already authenticated, just sync.
    if([session isAuthenticated]){
        self.authenticated = authenticated = YES;
        
        if (block) {
            block(authenticated, nil);
        }
        
        return;
    }
    
    [session authenticateWithViewController:controller preferRegistration:NO completion:^(NSError *error) {
        if (error || !session.isAuthenticated) {
            if (error.code == ENErrorCodeCancelled) {
                if (block) block(NO, nil);
            } else if (block) {
                block(NO, error);
            }
            
            GDLog(@"Evernote authentication failed with error: %@.", error);
            authenticated = self.authenticated = NO;
            
        } else {
            authenticated = self.authenticated = YES;
            if(block) block(YES, error);
        }
    }];
}
```

**Comment by kennir** [comment]
I have the same problem, need help pls

**Comment by everic** [comment]
Hi @tettoffensive 
I tried revoking my token in the web settings and could not repro any crash with the SDK sample app. I think automatically unauthentication is triggered when we got the ENStoreClientDidFailWithAuthenticationErrorNotification. Is there any specific API that you're using that caused the crash? Can you provide the stack trace of the crash? Or can you provide an sample app to demonstrate the issue? Thank you!

**Comment by everic** [comment]
@kennir Can you elaborate on this? Please check out my comment as @tettoffensive have not responded to me. Thank you!

**Comment by kennir** [comment]
@everic I have no idea, Is @tettoffensive says his own app ? 
I think the point is [ENSession isAuthentication] still returns YES after revoke token from web. not something crashed :)

**Comment by everic** [comment]
If this is the case, then I think it's by design. [ENSession isAuthenticated] is a local boolean flag to indicate whether you have a local authentication token. It cannot guarantee that you can absolutely get the contents with the token, as the token might be expired or revoked by the user. When such thing happens, the SDK will send out a ENStoreClientDidFailWithAuthenticationErrorNotification and we'll clear the local token and then [ENSession isAuthenticated] will return NO
