### ISSUE TITLE
Support for OS X

### ISSUE THREAD

**Issue by akac** [evernote/evernote-cloud-sdk-ios#96]
We have one project with two targets - OS X and iOS. We'd like to be able to have this one framework for both.

**Comment by everic** [comment]
We're excited and willing to support OS X target in the future but unfortunately at the moment we're only focusing on iOS. Thank you.

**Comment by akac** [comment]
I've rewritten your SDK to support OS X as it is. Its not that hard. Not even a few hours and its done. I think its short-sighted.

**Comment by everic** [comment]
@akac Can you do us a favor and submit a pull request?

**Comment by akac** [comment]
Possibly. Since I was reworking it, I took the liberty of having some aspects of the SDK to use our own methods/macros that we already use for cross-platform compiling (such as "PIImage" to cover both UIImage and NSImage). I'm compiling the code directly in our app, not as a framework as a result.

I'd probably be happier to send you my code zipped and let you guys do what you want with it…

**Comment by everic** [comment]
Ok. can you send to echeng@evernote.com. Thank you.

**Comment by akac** [comment]
Will do.

On Wed, Jun 17, 2015 at 2:59 PM, everic <notifications@github.com> wrote:

> Ok. can you send to echeng@evernote.com. Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evernote/evernote-cloud-sdk-ios/issues/96#issuecomment-112948347>
> .
>



-- 

*Alex Kac - **President and Founder*

*Web Information Solutions, Inc.*

**Comment by akac** [comment]
Done.

On Wed, Jun 17, 2015 at 2:59 PM, everic <notifications@github.com> wrote:

> Ok. can you send to echeng@evernote.com. Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evernote/evernote-cloud-sdk-ios/issues/96#issuecomment-112948347>
> .
>



-- 

*Alex Kac - **President and Founder*

*Web Information Solutions, Inc.*

**Comment by everic** [comment]
Thank you. @akac
