### ISSUE TITLE
share ENSession with App Extension

### ISSUE THREAD

**Issue by ilia510** [evernote/evernote-cloud-sdk-ios#97]
Hello, @everic,

Is there a possibility to share [ENSession sharedSession] between my main app and my app extension?

Otherwise I have to ask a user to login twice - once in the main app, second time with the first execution of my app extension?

Thanks in advance,
Ilia

**Comment by everic** [comment]
Yes, it's totally possible!

You need to configure in your app to share the ENPreferencesStore of the ENSession between your app and your extension. The ENPreferencesStore lives as a plist on your disk so you need to configure to share the file. And you also need to configure to share the keychain access between your app and your extension, so that the extension can read the access token from the keychain that's saved by the app.

You may need to fork the SDK in order to achieve this. Let me know if you have other questions and feel free to submit pull requests.

Thank you.

**Comment by ilia510** [comment]
Hello, @everic,

Thanks for the tip. However, I have not yet reached the level of Objective-C knowledge that I consider acceptable.

Would please help me out with those questions?

1) I know how to transfer ENPreferStore between app and extension. But how can I construct in the extension? ENPreferenceStore *store=??? - 
Maybe i should use the same approach as done in ENSession startup:


    self.preferences = SecurityApplicationGroupIdentifier ? [ENPreferencesStore preferenceStoreWithSecurityApplicationGroupIdentifier:SecurityApplicationGroupIdentifier] : [ENPreferencesStore defaultPreferenceStore];


2) So based on what I understood in evernote SDK for ENSession i need to add a new method:
    -initWithPrefStore:(ENPrefStore *)store

inside this method replicate a startup sequence from ENSession passing a ENPrefStore?

Or ENSDK will catch up (because I have shared a file, and ENSDK will see this file in the extension) when I run startup?

Thanks in advance,
Ilia

**Comment by everic** [comment]
You should not transfer the ENPreferenceStore between the app and the extension. They should share a single ENPreferenceStore.  In ENSession, in the startup function, you can see if you set the SecurityApplicationGroupIdentifier, the preference is set in a shareable way within the app group. Check Apple's documentation about how to share files between an iOS app and an iOS extension.

**Comment by ilia510** [comment]
All right, I did like you mentioned and it working fine using App Groups and method [ENSession setSecurityApplicationGroupIdentifier:<My App Group ID>].


One maybe last thing: I am building shared session in both - appDelegate for the app and ShareViewController for extension like this:

    [ENSession setSecurityApplicationGroupIdentifier:<My App Group ID>].
    [ENSession setSharedSessionConsumerKey:<> consumerSecret:<> optionalHost:nil];

Will it create two auth tokens? Keychain is shared between app and extension.

**Comment by everic** [comment]
@ilia510 No, it won't create two auth tokens. Setting the security application group identifier enables the token saved to the keychain readable by not only the app that's saving the token, but also the apps in the same security group. So in this way, both the extension and the host can read the same token from the iOS keychain. Setting the consumer key and the consumer secret is for OAuth purpose with Evernote, it's not relevant with the auth token itself.

**Comment by ilia510** [comment]
Thanks a lot, @everic. It works like a charm.

**Comment by everic** [comment]
You're welcome. @ilia510
