### ISSUE TITLE
support Japanese

### ISSUE THREAD

**Issue by taishiblue** [evernote/evernote-cloud-sdk-ios#98]
Please support Japanese.
I'm using ENSaveToEvernoteActivity.

「Save to Evernote」
→「Evernoteに保存する」

「Save」
→「保存」

「Add Tag」
→「タグを追加」

「Notebook」
→「ノートブック」

**Comment by everic** [comment]
Please provide the Japanese translation for these strings

"Login"

"Logout"

"Back" (go back to upper level)

"User info" (user's information)

"Tags"

"Save Activity" (save to Evernote activity)

"Create photo note"

"Clip web page"

"Search notes via keyword"

"View my notes"

"Save a customized note"

**Comment by taishiblue** [comment]
"Login"
ログイン

"Logout"
ログアウト

"Back" (go back to upper level)
戻る

"User info" (user's information)
アカウント情報

"Tags"
タグ

"Save Activity" (save to Evernote activity)
アクティビティを保存

"Create photo note"
新規写真ノート

"Clip web page"
Webページをクリップ

"Search notes via keyword"
ノートを検索

"View my notes"
ノートを見る

"Save a customized note"
It means "Save a edited note"?

**Comment by everic** [comment]
@taishiblue "Save a customized note" means a note that's customized by the application, for example, a recipe note created from a template.

**Comment by teraijun** [comment]
"Save a customized note"
テンプレートのノートで保存
